version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # Edge port (principal)
      - "4510-4559:4510-4559"  # Portas externas
    environment:
      - SERVICES=sqs,sns,dynamodb,lambda
      - DEBUG=${DEBUG-false}
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

  setup-resources:
    container_name: setup-resources
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./setup_localstack.sh:/setup_localstack.sh
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Espera pelo LocalStack ficar pronto
      sleep 10
      
      # Executa o script de configuração
      chmod +x /setup_localstack.sh
      sh /setup_localstack.sh
      "
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge 